const Data = [
  {
    id: 1,
    name: "Dior Sauvage",
    brand: "Dior",
    category: "Men",
    description: "A fresh and bold fragrance perfect for men.",
    price: 28000,
    discountPrice: 25000,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 15,
    rating: 4.8,
    reviewCount: 342,
    status: "active",
    soldThisMonth: 58,
    createdAt: "2025-01-12"
  },
  {
    id: 2,
    name: "Chanel Coco Mademoiselle",
    brand: "Chanel",
    category: "Women",
    description: "A luxurious feminine fragrance with warm floral notes.",
    price: 32000,
    discountPrice: 29999,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 8,
    rating: 4.9,
    reviewCount: 410,
    status: "active",
    soldThisMonth: 72,
    createdAt: "2025-02-04"
  },
  {
    id: 3,
    name: "Lattafa Raghba",
    brand: "Lattafa",
    category: "Unisex",
    description: "Sweet, woody Arabian perfume with long-lasting projection.",
    price: 3500,
    discountPrice: 2999,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 2,
    rating: 4.6,
    reviewCount: 210,
    status: "active",
    soldThisMonth: 93,
    createdAt: "2025-01-28"
  },
  {
    id: 4,
    name: "Afnan 9PM",
    brand: "Afnan",
    category: "Men",
    description: "Strong and seductive evening perfume for men.",
    price: 5500,
    discountPrice: 5200,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 0,
    rating: 4.7,
    reviewCount: 158,
    status: "inactive",
    soldThisMonth: 0,
    createdAt: "2025-02-10"
  },
  {
    id: 5,
    name: "Armaf Club de Nuit Intense",
    brand: "Armaf",
    category: "Men",
    description: "One of the best-selling long-lasting fresh perfumes.",
    price: 7500,
    discountPrice: 6999,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 22,
    rating: 4.5,
    reviewCount: 510,
    status: "active",
    soldThisMonth: 120,
    createdAt: "2025-01-05"
  },
  {
    id: 6,
    name: "Lattafa Yara",
    brand: "Lattafa",
    category: "Women",
    description: "Sweet and elegant scent popular among young women.",
    price: 4500,
    discountPrice: 4200,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 14,
    rating: 4.7,
    reviewCount: 261,
    status: "active",
    soldThisMonth: 66,
    createdAt: "2025-01-16"
  },
  {
    id: 7,
    name: "Al Rehab Silver",
    brand: "Al Rehab",
    category: "Unisex",
    description: "Cool and fresh deodorant/perfume for daily use.",
    price: 1200,
    discountPrice: 999,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 5,
    rating: 4.3,
    reviewCount: 180,
    status: "active",
    soldThisMonth: 45,
    createdAt: "2025-01-12"
  },
  {
    id: 8,
    name: "Naseem Oud Mood",
    brand: "Naseem",
    category: "Unisex",
    description: "Strong Arabian oud with long-lasting projection.",
    price: 3800,
    discountPrice: 3500,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 19,
    rating: 4.4,
    reviewCount: 134,
    status: "active",
    soldThisMonth: 51,
    createdAt: "2025-02-01"
  },
  {
    id: 9,
    name: "Rasasi Blue Lady",
    brand: "Rasasi",
    category: "Women",
    description: "Light and fresh perfume perfect for daily wear.",
    price: 2500,
    discountPrice: 2200,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 10,
    rating: 4.5,
    reviewCount: 95,
    status: "active",
    soldThisMonth: 30,
    createdAt: "2025-01-20"
  },
  {
    id: 10,
    name: "Ajmal Evoke",
    brand: "Ajmal",
    category: "Men",
    description: "Classic masculine scent with woody notes.",
    price: 6000,
    discountPrice: 5500,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 7,
    rating: 4.6,
    reviewCount: 120,
    status: "active",
    soldThisMonth: 40,
    createdAt: "2025-02-08"
  },
  {
    id: 11,
    name: "Lattafa Ana Abiyedh",
    brand: "Lattafa",
    category: "Men",
    description: "Bold and oriental fragrance for special occasions.",
    price: 4800,
    discountPrice: 4500,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 12,
    rating: 4.7,
    reviewCount: 85,
    status: "active",
    soldThisMonth: 55,
    createdAt: "2025-01-25"
  },
  {
    id: 12,
    name: "Swiss Arabian Shaghaf",
    brand: "Swiss Arabian",
    category: "Unisex",
    description: "Sweet and warm fragrance with vanilla notes.",
    price: 3300,
    discountPrice: 3100,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 18,
    rating: 4.5,
    reviewCount: 72,
    status: "active",
    soldThisMonth: 60,
    createdAt: "2025-02-02"
  },
  {
    id: 13,
    name: "Al Haramain L'Aventure",
    brand: "Al Haramain",
    category: "Men",
    description: "Fresh citrusy fragrance with a hint of musk.",
    price: 4900,
    discountPrice: 4700,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 9,
    rating: 4.6,
    reviewCount: 98,
    status: "active",
    soldThisMonth: 35,
    createdAt: "2025-01-30"
  },
  {
    id: 14,
    name: "Nabeel Black",
    brand: "Nabeel",
    category: "Women",
    description: "Intense and long-lasting fragrance for evening wear.",
    price: 4100,
    discountPrice: 3800,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 6,
    rating: 4.4,
    reviewCount: 56,
    status: "active",
    soldThisMonth: 28,
    createdAt: "2025-01-18"
  },
  {
    id: 15,
    name: "Al Rehab Golden",
    brand: "Al Rehab",
    category: "Unisex",
    description: "Warm and sweet fragrance suitable for any occasion.",
    price: 1500,
    discountPrice: 1200,
    image: "https://elyscents.pk/cdn/shop/files/3perfume.jpg?v=1760181185&width=360",
    stock: 20,
    rating: 4.3,
    reviewCount: 67,
    status: "active",
    soldThisMonth: 50,
    createdAt: "2025-02-05"
  }
];



export default Data